# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker connection'
        repository: 'juanlajud/jumbodemoapp:1.1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |    
          $(tag)
- stage: Provision
  displayName: 
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: 'Provitioning container instance'
    pool: 
      vmimage: ubuntu-latest
    variables: 
    - group: TerraformServicePrincipleVars
    steps: 
    - script: |
        set -e
        terraform init -input=false
        terraform apply -input=false -auto-approve
      name: 'terraform-run'
      displayName: 'Run Terraform'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      